spring:
  application:
    name: AUTH-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_ADDRESS:http://localhost:9296}


  datasource:
#    username: AXS1QFH
#    password: 123456
#    url: jdbc:postgresql://${INTERNAL_URL:localhost}:5432/jwt_security
    username: ${DB_USERNAME:AXS1QFH}
    password: ${DB_PASSWORD:123456}
    url: ${DB_HOST:jdbc:postgresql://${INTERNAL_URL:localhost}:5432/jwt_security}
#    url: jdbc:postgresql://jwtsecurity.cknism0rgni6.us-east-1.rds.amazonaws.com:5432/jwtsecurity
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days


server:
  port: 8086

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}




